const MeetingActionTypes = {
    ADD_NEW_MEETING: 'ADD_NEW_MEETING',
    ADD_MEETING_TO_SELECTED:'ADD_MEETING_TO_SELECTED',
    REMOVE_MEETING_FROM_SELECTED:'REMOVE_MEETING_FROM_SELECTED',
    ADD_TRANS_FEES_COUNT:'ADD_TRANS_FEES_COUNT',
    ADD_TRANS_MEANS_COUNT:'ADD_TRANS_MEANS_COUNT',
    ADD_ACCOM_FEES_COUNT:'ADD_ACCOM_FEES_COUNT',
    SET_DATA: 'SETD_ATA',
    SET_MULTIPE_DATA:'SET_MULTIPE_DATA',
    DELETE_MEETINGS: 'DELETE_MEETINGS'
}

export default MeetingActionTypes;